/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-03-11 22:54:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Miniature — Inscription</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <nav>\n");
      out.write("        <a href=\"/\" class=\"nav__logo\">Miniature</a>\n");
      out.write("        <a href=\"/\" class=\"nav__back\">← Retour</a>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"page\">\n");
      out.write("\n");
      out.write("        <div class=\"panel-image gradient-left\">\n");
      out.write("            <img src=\"https://simplonline.co/_next/image?url=https%3A%2F%2Fsimplonline-v3-prod.s3.eu-west-3.amazonaws.com%2Fmedia%2Fimage%2Fwebp%2Fcomfyui-00455-66bf526b2172e266974676-69b1218a1b993958720385.webp&w=1280&q=75\"\n");
      out.write("                 alt=\"Miniature illustration\">\n");
      out.write("            <div class=\"panel-image__quote\">\n");
      out.write("                <p>Rejoignez une communauté<br>qui partage l'essentiel.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"panel-form\">\n");
      out.write("\n");
      out.write("            <p class=\"label\">Nouveau compte</p>\n");
      out.write("            <h1>Créer <em>votre espace</em></h1>\n");
      out.write("            <p class=\"subtitle\">Quelques secondes suffisent.</p>\n");
      out.write("\n");
      out.write("            ");
 if ("true".equals(request.getParameter("error"))) { 
      out.write("\n");
      out.write("                <div class=\"error-msg\">Veuillez vérifier vos informations.</div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <form action=\"/register\" method=\"post\">\n");
      out.write("\n");
      out.write("                <div class=\"field\">\n");
      out.write("                    <label for=\"login\">Login</label>\n");
      out.write("                    <input type=\"text\" name=\"login\" id=\"login\"\n");
      out.write("                           placeholder=\"Entre 4 et 8 caractères\"\n");
      out.write("                           required minlength=\"4\" maxlength=\"8\">\n");
      out.write("                    <p class=\"field__hint\">4 à 8 caractères</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"field\">\n");
      out.write("                    <label for=\"email\">Adresse email</label>\n");
      out.write("                    <input type=\"email\" name=\"email\" id=\"email\"\n");
      out.write("                           placeholder=\"vous@exemple.com\"\n");
      out.write("                           pattern=\"[-a-zA-Z0-9._]+@[-a-zA-Z0-9._]+\\.[a-zA-Z.]{2,15}\"\n");
      out.write("                           required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"field\">\n");
      out.write("                    <label for=\"pass\">Mot de passe</label>\n");
      out.write("                    <input type=\"password\" id=\"pass\" name=\"password\"\n");
      out.write("                           placeholder=\"8 caractères minimum\"\n");
      out.write("                           minlength=\"8\" required>\n");
      out.write("                    <p class=\"field__hint\">8 caractères minimum</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"field\">\n");
      out.write("                    <label for=\"passConf\">Confirmer le mot de passe</label>\n");
      out.write("                    <input type=\"password\" id=\"passConf\" name=\"passwordConf\"\n");
      out.write("                           placeholder=\"Répétez votre mot de passe\"\n");
      out.write("                           minlength=\"8\" required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"btn-submit\">Créer mon compte</button>\n");
      out.write("\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <p class=\"form-footer\">\n");
      out.write("                Déjà membre ? <a href=\"login.jsp\">Se connecter</a>\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
