/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.simplon;

import java.io.File;

import org.apache.catalina.Context;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.WebResourceRoot;
import org.apache.catalina.startup.Tomcat;
import org.apache.catalina.webresources.DirResourceSet;
import org.apache.catalina.webresources.StandardRoot;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Tomcat tomcat = new Tomcat();
        tomcat.setPort(8080);
        tomcat.getConnector();

        File publicFolder = new File("src/main/java/fr/simplon/presentation/views/webapp/");
        if (!publicFolder.exists()) {
            publicFolder.mkdirs();
        }

        Context ctx = tomcat.addWebapp("", publicFolder.getAbsolutePath());
        ctx.setReloadable(true);

        File classesFolder = new File("build/classes/java/main");
        WebResourceRoot resources = new StandardRoot(ctx);
        resources.addPreResources(new DirResourceSet(
                resources,
                "/presentation/views/webapp/WEB-INF/classes",
                classesFolder.getAbsolutePath(),
                "/"));
        ctx.setResources(resources);

        try {
            tomcat.start();
        } catch (LifecycleException e) {
            e.printStackTrace();
        }
        tomcat.getServer().await();
    }
}
